export enum configParamsType {
  EMAIL = 'EMAIL',
  PAYMENT = 'PROJECT_PAYMENT',
  INSURANCE = 'PROJECT_INSURANCE',
  PRIORITY = 'PROJECT_PRIORITY',
  PROFIT_TARGET = 'PROJECT_PROFIT_TARGET',
  OTHER = 'OTHER',
}
