export const listDemoPages = [
  {
    type: 'col-lg-3',
    link: "./digital-agency",
    img: "assets/images/demos/home1.jpg",
    name: "Digital Agency",
    category: 'demo',
  },
  {
    type: 'col-lg-3',
    link: "./creative-agency",
    img: "assets/images/demos/home2.jpg",
    name: "Creative Agency",
    category: 'demo',
  },
  {
    type: 'col-lg-3',
    link: "./it-agency",
    img: "assets/images/demos/home3.jpg",
    name: "IT Agency",
    category: 'demo',
  },
  {
    type: 'col-lg-3',
    link: "./marketing-agency",
    img: "assets/images/demos/home4.jpg",
    name: "Marketing Agency",
    category: 'demo',
  },
  {
    type: 'col-lg-6',
    link: "./portfolio-agency",
    img: "assets/images/demos/home5.jpg",
    name: "Portfolio Agency",
    category: 'demo',
  },
  {
    type: 'col-lg-6',
    link: "./studio-agency",
    img: "assets/images/demos/home6.jpg",
    name: "Studio Agency",
    category: 'demo',
  },
  {
    type: 'col-lg-3',
    link: "./business-agency",
    img: "assets/images/demos/home7.jpg",
    name: "Business Agency",
    category: 'demo',
  },
  {
    type: 'col-lg-3',
    link: "./startup-agency",
    img: "assets/images/demos/home8.jpg",
    name: "Startup Agency",
    category: 'demo',
  },
  {
    type: 'col-lg-3',
    link: "./freelancer-portfolio",
    img: "assets/images/demos/home9.jpg",
    name: "Freelancer Portfolio",
    category: 'demo',
  },
  {
    type: 'col-lg-3',
    link: "./software-startup",
    img: "assets/images/demos/home10.jpg",
    name: "Software Startup",
    category: 'demo',
  },
  {
    type: 'col-lg-3',
    link: "./digital-marketing",
    img: "assets/images/demos/home11.jpg",
    name: "Digital Marketing",
    category: 'demo',
  },
  {
    type: 'col-lg-3',
    link: "./business-consulting",
    img: "assets/images/demos/home12.jpg",
    name: "Business Consulting",
    category: 'demo',
  },
  {
    type: 'col-lg-3',
    link: "./app-showcase",
    img: "assets/images/demos/home13.jpg",
    name: "App Showcase",
    category: 'demo',
  },
  {
    type: 'col-lg-3',
    link: "./personal-portfolio",
    img: "assets/images/demos/home14.jpg",
    name: "Personal Portfolio",
    category: 'demo',
  },
  {
    type: 'col-lg-3',
    link: "./saas-startup",
    img: "assets/images/demos/home15.jpg",
    name: "SaaS Startup",
    category: 'demo',
  },
  {
    type: 'col-lg-3',
    link: "./cyber-security-agency",
    img: "assets/images/demos/home16.jpg",
    name: "Cyber Security Agency",
    category: 'demo',
  },
];
