export const listClientesPages = [
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/servicos/cliente-teatroportoseguro.jpg",
    name: "Teatro Porto Seguro",
    category: 'serviço',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/servicos/cliente-servicos-serasa.jpg",
    name: "Serasa Experian",
    category: 'serviço',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/servicos/cliente-ticket.jpg",
    name: "Ticket",
    category: 'serviço',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/servicos/cliente-servicos-capemisa.jpg",
    name: "Capemisa",
    category: 'serviço',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/servicos/cliente-servicos-lance.jpg",
    name: "Lance",
    category: 'serviço',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/servicos/cliente-servicos-acelero.jpg",
    name: "Acelero",
    category: 'serviço',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/servicos/cliente-vitta.jpg",
    name: "Vitta",
    category: 'serviço',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/servicos/cliente-voopter.jpg",
    name: "Voopter",
    category: 'serviço',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/servicos/cliente-servicos-bernhoeft.jpg",
    name: "Bernhoeft",
    category: 'serviço',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/servicos/cliente-servicos-gazeta.jpg",
    name: "Gazeta Online",
    category: 'serviço',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/servicos/cliente-servicos-fortbras.jpg",
    name: "Fortbras",
    category: 'serviço',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/servicos/cliente-servicos-conservo.jpg",
    name: "Soluções Concervo",
    category: 'serviço',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/industria/cliente-acrilex.jpg",
    name: "Acrilex",
    category: 'Indústria',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/industria/cliente-royalenfield.jpg",
    name: "Royal Enfield",
    category: 'Indústria',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/industria/cliente-ambev.jpg",
    name: "Ambev",
    category: 'Indústria',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/industria/cliente-samsung.jpg",
    name: "Samsung",
    category: 'Indústria',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/industria/cliente-vale.jpg",
    name: "Vale",
    category: 'Indústria',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/industria/cliente-fornodeminas.jpg",
    name: "Forno de Minas",
    category: 'Indústria',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/industria/cliente-uau.jpg",
    name: "UAU",
    category: 'Indústria',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/industria/cliente-copel.jpg",
    name: "Copel",
    category: 'Indústria',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/tech/cliente-arquivar.jpg",
    name: "Arquivar",
    category: 'Tecnologia',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/tech/cliente-avec.jpg",
    name: "AVEC",
    category: 'Tecnologia',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/tech/cliente-confitec.jpg",
    name: "Confitec",
    category: 'Tecnologia',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/tech/home16.jpg",
    name: "Cyber",
    category: 'Tecnologia',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/tech/cliente-easytaxy.jpg",
    name: "Easy Taxi (99)",
    category: 'Tecnologia',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/tech/cliente-ecommercebrasil.jpg",
    name: "Ecommerce Brasil",
    category: 'Tecnologia',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/tech/cliente-imasters.jpg",
    name: "IMasters",
    category: 'Tecnologia',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/tech/cliente-mercadopago.jpg",
    name: "Mercado Pago",
    category: 'Tecnologia',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/tech/cliente-nicbr.jpg",
    name: "Nic.BR",
    category: 'Tecnologia',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/tech/cliente-sml.jpg",
    name: "SML",
    category: 'Tecnologia',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/tech/cliente-upx.jpg",
    name: "SML",
    category: 'UPX',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/varejo/cliente-estrela.jpg",
    name: "Estrela",
    category: 'Varejo',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/varejo/cliente-americanas.jpg",
    name: "Americanas.com",
    category: 'Varejo',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/varejo/cliente-petz.jpg",
    name: "Petz",
    category: 'Varejo',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/varejo/cliente-ciadoslivros.jpg",
    name: "Cia dos Livros",
    category: 'Varejo',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/varejo/cliente-arclube.jpg",
    name: "ArClube",
    category: 'Varejo',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/educacao/cliente-positivo.jpg",
    name: "Universidade Positivo",
    category: 'Educação',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/educacao/cliente-unyleya.jpg",
    name: "Faculdade Unyleya",
    category: 'Educação',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/gov/cliente-ronaldmcdonald.jpg",
    name: "Casa Ronald McDonald",
    category: 'Gov/Ongs',
  },
  {
    type: 'col-lg-3',
    link: "./",
    img: "assets/images/partners/gov/cliente-detranrj.jpg",
    name: "Detran-Rj",
    category: 'Gov/Ongs',
  },
];
