export enum CountryCodeSourceEnum {
  FROM_DEFAULT_COUNTRY = "FROM_DEFAULT_COUNTRY",
  FROM_NUMBER_WITHOUT_PLUS_SIGN = "FROM_NUMBER_WITHOUT_PLUS_SIGN",
  FROM_NUMBER_WITH_IDD = "FROM_NUMBER_WITH_IDD",
  FROM_NUMBER_WITH_PLUS_SIGN = "FROM_NUMBER_WITH_PLUS_SIGN",
  UNSPECIFIED = "UNSPECIFIED"
}
